apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nim-pvc
  namespace: runai-medo
  labels:
    app.kubernetes.io/part-of: medw
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi   # NIM engine cache for LLM model
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nim-embed-pvc
  namespace: runai-medo
  labels:
    app.kubernetes.io/part-of: medw
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi   # NIM engine cache for 1B embedding model
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nim-reranker-pvc
  namespace: runai-medo
  labels:
    app.kubernetes.io/part-of: medw
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi   # NIM engine cache for 1B reranker model
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pvc
  namespace: runai-medo
  labels:
    app.kubernetes.io/part-of: medw
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi    # Milvus Lite embedded database file
